image_root: '../dataset/ElsCap/imgs'
ann_root: '../annotation/blip'
coco_gt_root: '../annotation/elscap_gt'

# set pretrained as a file path or an url
pretrained: '../output/blip_mmicap/elscap/checkpoint_best.pth'

# size of vit model; base or large
med_config: '../blip_mmicap/configs/med_config.json'
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 6
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 40  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 100
