image_root: '../dataset/ElsCap/imgs'
ann_root: './annotation/blip'
coco_gt_root: './annotation/elscap_gt'

# set pretrained as a file path or an url
pretrained: "./output/lstm_att_our/elscap/checkpoint_best.pth"

batch_size: 32
init_lr: 1e-5
image_size: 224

embed_size: 300
attention_dim: 256
encoder_dim: 2048
decoder_dim: 512

# generation configs
max_length: 40 

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 50
